PREGUNTA_CHISME = "¿Cuenta un chisme? (preferiblemente relacionado con gente del grupo)"

TODAS = [
    "Nombre completo",
    "Edad",
    "3 cosas que te den miedo",
    "4 cosas que ames",
    "4 cosas que te diviertan",
    "4 cosas que te aburran",
    "Tus mejores amigos:",
    "Orientación sexual",
    "Tu primera cita",
    "¿Cuál es tu estatura?",
    "Algo que extrañes:",
    "¿Cuándo naciste?",
    "Color fav",
    "¿Tienes platonic@s?",
    "Frase favorita:",
    "Lugar favorito:",
    "¿Usas el sarcasmo?",
    "¿Qué estás escuchando en este momento?",
    "La primera cosa en que te fijas en las personas:",
    "Talla de zapatos",
    "Color de ojos:",
    "Color de cabello:",
    "¿Has hecho llamadas de broma?",
    "Película fav",
    "Canción fav",
    "Banda o cantante favorito:",
    "¿Cómo te sientes ahora mismo?",
    "Alguien que ames:",
    "Tu relación actual:",
    "¿Cómo es la relación con tus papás?",
    "¿Festividad favorita?",
    "¿Te gustaría hacerte un tatuaje? ¿Cuál?",
    "¿Te llevas bien con tu ex?",
    "¿Recibes mensajes de buenos días/buenas noches?",
    "¿Has besado a la última persona a la que le mandaste mensaje?",
    "¿Cuándo fue la última vez que tomaste de la mano a alguien?",
    "¿Cuánto tiempo tardas en alistarte?",
    "¿Te has rasurado las piernas los últimos tres días?",
    "¿Dónde estás ahora mismo?",
    "¿Vives con tus padres?",
    "¿Estás emocionado por algo?",
    "¿Tienes alguien del sexo opuesto a quien le puedes contar todo?",
    "¿Has fingido una sonrisa?",
    "¿Cuándo fue la última vez que abrazaste a alguien?",
    "¿Qué harías si la última persona que besaste estuviera frente a ti?",
    "¿Hay alguien en quien confías pero sabes que no deberías?",
    "Algo que no te gustó de tu día:",
    "¿Cuál es tu signo zodiacal?",
    "¿Cuál es tu número de la suerte?",
    "¿Tienes mascotas?",
    "¿Dónde naciste?",
    "¿Cuántos pares de zapatos tienes?",
    "¿De qué se trató el último sueño que tuviste?",
    "¿Tienes algún talento?",
    "¿Quién sería tu pareja ideal?",
    "¿Quieres hijos?",
    "¿Te casarías por la iglesia?",
    "¿Crees en alguna religión?",
    "¿Te han internado en el hospital?",
    "¿Has roto la ley?",
    "¿Has conocido a alguien famoso?",
    "¿Cuánto tiempo tardas bañándote?",
    "Color de la ropa interior que llevas puesta:",
    "¿Te gustaría ser famoso?",
    "¿Qué tipo de música te gusta?",
    "Palabra que más uses:",
    "¿Tienes mucha autoestima?",
    "¿Cuál es tu dulce favorito?",
    "Papitas favoritas:",
    "¿Soda o agua?",
    "Comida favorita:",
    "¿Cantas cuando te bañas?",
    "¿Hablas solo?",
    "Mayor miedo:",
    "¿Eres chismoso?",
    "Mejor película dramática que hayas visto:",
    "¿Cabello largo o corto?",
    "¿Materia favorita de la escuela?",
    "¿Alguien te ha influenciado a ser la persona que eres?",
    "¿Qué cambiarías de ti?",
    "¿Qué harías si te quedara un día de vida?",
    "¿En qué década te hubiera gustado vivir?",
    "¿Con quién te llevas mejor en tu familia?",
    "¿Quién crees que te conoce muy bien?",
    "¿Qué te gusta de ti?",
    "¿Qué te gusta de tu mejor amigo?",
    "¿Qué quieres ser de grande?",
    "¿Te gusta que te aconsejen?",
    "¿Das buenos consejos?",
    "¿Crees en el amor a primera vista?",
    "¿Crees en las parejas ideales?",
    "¿Crees en los horóscopos?",
    "¿Qué te atrae del sexo opuesto?",
    "¿Qué harías si fueras del sexo opuesto por un día?",
    "Algo que te gustaría aprender a hacer:",
    "Algo que te da miedo hacer:",
    "¿Cuándo y por qué fue la última vez que lloraste?",
    "Algo que te haga reír:",
    "Algo que hayas hecho y te haya avergonzado:",
    "¿Te arrepientes de algo?",
    "¿Qué es lo más loco que has hecho?",
    "¿Te da vergüenza hablarle a desconocidos?",
    "¿Cuál es tu chiste favorito?",
    "¿Gatos o perros?",
    "¿Qué animal te gustaría ser?",
    "Serie favorita:",
    "¿Cómo crees que te describen tus papás?",
    "¿Qué momento te gustaría repetir?",
    "Algo que crees pero que los demás no:",
    "¿Crees en los ovnis?",
    "¿Te gustan los atardeceres?",
    "Algo que te haga único ante los demás:",
    "¿Qué piensas que le hace falta a tu vida?",
    "¿Te gusta ver las estrellas?",
    "¿Frío o calor?",
    "¿La primera vez que viste tu película fav?",
    "Tu primer beso:",
    "La persona que más has querido:",
    "Tu mejor cumpleaños:",
    "Tu peor cumpleaños:",
    "Tu mayor inseguridad:",
    "Algo de lo que te sientas orgulloso:",
    "Cosas que te gustan de tu cuerpo:",
    "La pelea más grande que has tenido:",
    "Mejor y peor sueño que has tenido:",
    "La primera vez que te acostaste con alguien o cómo te gustaría que pasara:",
    "Tus mejores vacaciones:",
    "Un recuerdo feliz y uno triste:",
    "La mejor fiesta a la que hayas ido:",
    "Algo que te pasó en la primaria:",
    "Tu mejor recuerdo de la secundaria:",
    "¿Dónde te gustaría estudiar?",
    "¿Has decepcionado a alguien?",
    "¿Te han decepcionado?",
    "La mentira más grande que hayas dicho:",
    "Algo que te hayan dicho y haya significado mucho para ti:",
    "¿Te han puesto el cuerno?",
    "Tu parte favorita del cuerpo de alguien más:",
    "Cosas que te excitan:",
    "Cosas que te bajan las ganas:",
    "¿Crees en el cielo y el infierno?",
    "Tu mejor recuerdo de la infancia:",
    "¿Qué haces cuando estás triste?",
    "Mayor dolor físico que has tenido:",
    "Cosas que desearías dejar de hacer:",
    "Gustos o placeres secretos:",
    "Sabor de nieve favorito:",
    "Alguien con quien pensabas que ibas a hablar siempre:",
    "Canciones que te recuerden a personas:",
    "¿Te gusta dormir en el piso?",
    "¿Te gusta caminar descalzo?",
    "¿Te gusta barrer?",
    "¿Te gusta limpiar?",
    "Cosas que desearías haber sabido antes:",
    "¿Te bañas todos los días?",
    "¿Te gusta regar las plantas?",
    "¿A qué hora te levantas?",
    "¿Eres sincero?",
    "El final de algo en tu vida:",
    "¿Cuál es tu mayor logro hasta ahora?",
    "¿Qué libro te ha marcado la vida?",
    "¿Tienes alguna fobia?",
    "¿Cuál es tu recuerdo más antiguo?",
    "¿Qué superpoder te gustaría tener?",
    "¿Cuál es tu peor hábito?",
    "¿Qué es lo primero que haces al despertar?",
    "¿Tienes algún objeto con valor sentimental?",
    "¿Cuál ha sido tu mayor decepción amorosa?",
    "¿Qué te gustaría que dijeran de ti en tu funeral?",
    "¿Has tenido alguna experiencia paranormal?",
    "¿Cuál es tu forma de demostrar cariño?",
    "¿Qué canción describe tu vida?",
    "¿Cuál es tu guilty pleasure?",
    "¿Qué país te gustaría visitar?",
    "¿Cuál es tu peor defecto?",
    "¿Cuál es tu mejor virtud?",
    "¿Qué harías con un millón de dólares?",
    "¿Cuál es tu mayor secreto?",
    "¿Tienes algún ritual antes de dormir?",
    "¿Cuál es tu red social favorita?",
    "¿Cómo te imaginas en 10 años?",
    "¿Cuál ha sido el mejor consejo que te han dado?",
    "¿Qué te hace sentir vivo?",
    "¿Cuál es tu hora favorita del día?",
    "¿Qué es lo que más valoras en una amistad?",
    "¿Has mentido hoy?",
    "¿Cuál es tu videojuego favorito?",
    "¿Qué talento te gustaría tener?",
    "¿Cuál es tu bebida favorita?",
    "¿Prefieres playa o montaña?",
    "¿Cuál es tu emoji más usado?",
    "¿Qué es lo más raro que has comido?",
    "¿Tienes algún apodo? ¿Cuál?",
    "¿Cuál es tu estación del año favorita?",
    "¿Qué es lo que más extrañas de tu infancia?",
    "¿Has tenido un amor platónico imposible?",
    "¿Cuál es tu postre favorito?",
    "¿Qué te hace perder la noción del tiempo?",
    "¿Cuál ha sido tu peor cita?",
    "¿Qué es lo más valiente que has hecho?",
    "¿Prefieres té o café?",
    "¿Tienes algún hobby?",
    "¿Te gusta viajar?",
    "¿Qué libro has leído recientemente?",
    "¿Eres madrugador?",
    "¿Cuál es tu trabajo o estudio?",
    "¿Practicas algún deporte?",
    "¿Invierno o verano?",
    "¿Tienes hermanos?",
    "¿Crees en el destino?",
    "¿Dulce o salado?",
    "¿Perdonarías una traición?",
    "¿Qué te motiva en la vida?",
    "¿Ciudad o campo?",
    "¿Has tenido una experiencia que te cambió la vida?",
    "¿Qué opinas sobre la honestidad absoluta?",
    "¿Libro o película?",
    "¿Mentirías para proteger a alguien?",
    "¿Amor o dinero?",
    "¿Has roto alguna promesa importante?",
    "¿Crees en la monogamia?",
    "¿Beso en la primera cita o no?",
    "¿Has tenido un amor no correspondido?",
    "¿Qué buscas en una pareja?",
    "¿Fantasía romántica favorita?",
    "¿Has probado citas en línea?",
    "¿Qué te atrae físicamente de alguien?",
    "¿Lencería o desnudo?",
    "¿Cuál es tu zona erógena preferida?",
    "¿Has practicado sexo casual?",
    "¿Qué fantasía sexual no has cumplido?",
    "¿Dominante o sumiso?",
    "¿Has usado juguetes sexuales?",
    "¿Te excita el riesgo?",
    "¿Qué posición sexual prefieres?",
    "¿Trío o no?",
    "¿Cuál es tu secreto sexual más oscuro?",
]

RAPIDAS = [
    "Nombre completo",
    "Edad",
    "¿Cuál es tu estatura?",
    "¿Cuándo naciste?",
    "Color fav",
    "Talla de zapatos",
    "Color de ojos",
    "Color de cabello",
    "¿Cuál es tu signo zodiacal?",
    "¿Cuál es tu número de la suerte?",
    "¿Dónde naciste?",
    "¿A qué hora te levantas?",
    "¿Tienes platonic@s?",
    "¿Usas el sarcasmo?",
    "¿Has hecho llamadas de broma?",
    "¿Te llevas bien con tu ex?",
    "¿Te has rasurado las piernas los últimos tres días?",
    "¿Vives con tus padres?",
    "¿Estás emocionado por algo?",
    "¿Has fingido una sonrisa?",
    "¿Tienes mascotas?",
    "¿Quieres hijos?",
    "¿Te casarías por la iglesia?",
    "¿Crees en alguna religión?",
    "¿Te han internado en el hospital?",
    "¿Has roto la ley?",
    "¿Has conocido a alguien famoso?",
    "¿Te gustaría ser famoso?",
    "¿Tienes mucha autoestima?",
    "¿Cantas cuando te bañas?",
    "¿Hablas solo?",
    "¿Eres chismoso?",
    "¿Te gusta que te aconsejen?",
    "¿Das buenos consejos?",
    "¿Crees en el amor a primera vista?",
    "¿Crees en las parejas ideales?",
    "¿Crees en los horóscopos?",
    "¿Te arrepientes de algo?",
    "¿Te da vergüenza hablarle a desconocidos?",
    "¿Crees en los ovnis?",
    "¿Te gustan los atardeceres?",
    "¿Te gusta ver las estrellas?",
    "¿Has decepcionado a alguien?",
    "¿Te han decepcionado?",
    "¿Te han puesto el cuerno?",
    "¿Crees en el cielo y el infierno?",
    "¿Te gusta dormir en el piso?",
    "¿Te gusta caminar descalzo?",
    "¿Te gusta barrer?",
    "¿Te gusta limpiar?",
    "¿Te bañas todos los días?",
    "¿Te gusta regar las plantas?",
    "¿Eres sincero?",
    "¿Soda o agua?",
    "¿Cabello largo o corto?",
    "¿Gatos o perros?",
    "¿Frío o calor?",
    "¿Playa o montaña?",
    "¿Has mentido hoy?",
    "¿Té o café?",
    "¿Te gusta viajar?",
    "¿Eres madrugador?",
    "¿Practicas algún deporte?",
    "¿Invierno o verano?",
    "¿Tienes hermanos?",
    "¿Crees en el destino?",
    "¿Dulce o salado?",
    "¿Perdonarías una traición?",
    "¿Ciudad o campo?",
    "¿Libro o película?",
    "¿Mentirías para proteger a alguien?",
    "¿Amor o dinero?",
    "¿Crees en la monogamia?",
    "¿Beso en la primera cita o no?",
    "¿Has probado citas en línea?",
]
